version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "weekly-bestseller-updates-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-d94p80c3z04f"
s3_prefix = "weekly-bestseller-updates-sam-app"
region = "us-east-1"
profile = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

