version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "weekly-bestseller-updates-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1j3ffa391jrgs"
s3_prefix = "weekly-bestseller-updates-sam-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
