AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Example SAM stack'
Resources:
  WeeklyBestSellerUpdate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      # Any env variables you want to use must be defined here (and then their values can be overridden in env.json)
      Environment:
        Variables:
          NYT_API_KEY: "USE_THE_ACTUAL_API_KEY"
          DYNAMO_TABLE_NAME: "USE_THE_ACTUAL_TABLE_NAME"
          SOURCE_EMAIL_ADDRESS: "USE_MY_ACTUAL_EMAIL_ADDRESS"
      Policies:
      - DynamoDBCrudPolicy:
          TableName: weekly-bestseller-updates
      - SESCrudPolicy:
          IdentityName: # Fill this in before executing
