version: 2.1

executors:
  yarn_pr_creator:
    docker:
      - image: circleci/node

commands:
  update_packages:
    steps:
      - run:
          name: Raise PRs for package updates
          command: |
            docker run -e RENOVATE_TOKEN=${RENOVATE_TOKEN} renovate/renovate --platform=github --log-level=debug risafj/weekly-bestseller-update

jobs:
  yarn_upgrade_pr:
    executor: yarn_pr_creator
    steps:
      - checkout
      - update_packages

workflows:
  version: 2
  yarn_upgrade_pr:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - master

    jobs:
      - yarn_upgrade_pr
